obj-$(CONFIG_TITANVOIP)	+= titan_dsp.o titan_tiuhal.o titan_mxpmod.o legerity/ titan_hwan.o

titan_dsp-objs := hwdsp.o
titan_tiuhal-objs := tiuhal.o legerity/sys_service.o
titan_mxpmod-objs := mxpmod.o
titan_hwan-objs := tiuhw_an.o
