obj-$(CONFIG_AR7VOIP)	+= ar7dsp.o ar7hal.o ar7mxpmod.o legerity/ ar7hwan.o testapp.o

ar7dsp-objs := hwdsp.o
ar7hal-objs := tiuhal.o legerity/sys_service.o
ar7mxpmod-objs := mxpmod.o
ar7hwan-objs := tiuhw_an.o
testapp-objs := test.o
